os: linux
sudo: false
language: python
python:
    - "3.6"

install:
    - pip install pycodestyle

script:
    - pycodestyle torchpf/ --ignore=E501,E226

cache:
    - pip

notifications:
    email: false
